var Zepto=function(){function g(a){return null==a?String(a):N[V.call(a)]||"object"}function h(a){return"function"==g(a)}function z(a){return null!=a&&a==a.window}function w(a){return null!=a&&a.nodeType==a.DOCUMENT_NODE}function q(a){return"object"==g(a)}function A(a){return q(a)&&!z(a)&&Object.getPrototypeOf(a)==Object.prototype}function C(a){return"number"==typeof a.length}function r(a){return d.call(a,function(a){return null!=a})}function p(a){return a.replace(/::/g,"/").replace(/([A-Z]+)([A-Z][a-z])/g,
"$1_$2").replace(/([a-z\d])([A-Z])/g,"$1_$2").replace(/_/g,"-").toLowerCase()}function u(a){return a in O?O[a]:O[a]=new RegExp("(^|\\s)"+a+"(\\s|$)")}function D(a,b){return"number"!=typeof b||W[p(a)]?b:b+"px"}function F(a){return"children"in a?c.call(a.children):e.map(a.childNodes,function(a){if(1==a.nodeType)return a})}function E(a,b,f){for(l in b)f&&(A(b[l])||G(b[l]))?(A(b[l])&&!A(a[l])&&(a[l]={}),G(b[l])&&!G(a[l])&&(a[l]=[]),E(a[l],b[l],f)):b[l]!==s&&(a[l]=b[l])}function x(a,b){return null==b?
e(a):e(a).filter(b)}function v(a,b,f,c){return h(b)?b.call(a,f,c):b}function y(a,b){var f=a.className||"",c=f&&f.baseVal!==s;if(b===s)return c?f.baseVal:f;c?f.baseVal=b:a.className=b}function H(a){var b;try{return a?"true"==a||("false"==a?!1:"null"==a?null:/^0/.test(a)||isNaN(b=Number(a))?/^[\[\{]/.test(a)?e.parseJSON(a):a:b):a}catch(f){return a}}function I(a,b){b(a);for(var f=0,c=a.childNodes.length;f<c;f++)I(a.childNodes[f],b)}var s,l,e,B,t=[],c=t.slice,d=t.filter,k=window.document,m={},O={},W=
{"column-count":1,columns:1,"font-weight":1,"line-height":1,opacity:1,"z-index":1,zoom:1},P=/^\s*<(\w+|!)[^>]*>/,J=/^<(\w+)\s*\/?>(?:<\/\1>|)$/,X=/<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/ig,R=/^(?:body|html)$/i,Y=/([A-Z])/g,Z="val css html text data width height offset".split(" "),Q=k.createElement("table"),S=k.createElement("tr"),T={tr:k.createElement("tbody"),tbody:Q,thead:Q,tfoot:Q,td:S,th:S,"*":k.createElement("div")},aa=/complete|loaded|interactive/,ba=/^[\w-]*$/,
N={},V=N.toString,n={},L,M,U=k.createElement("div"),ca={tabindex:"tabIndex",readonly:"readOnly","for":"htmlFor","class":"className",maxlength:"maxLength",cellspacing:"cellSpacing",cellpadding:"cellPadding",rowspan:"rowSpan",colspan:"colSpan",usemap:"useMap",frameborder:"frameBorder",contenteditable:"contentEditable"},G=Array.isArray||function(a){return a instanceof Array};n.matches=function(a,b){if(!b||!a||1!==a.nodeType)return!1;var f=a.webkitMatchesSelector||a.mozMatchesSelector||a.oMatchesSelector||
a.matchesSelector;if(f)return f.call(a,b);var c;c=a.parentNode;(f=!c)&&(c=U).appendChild(a);c=~n.qsa(c,b).indexOf(a);f&&U.removeChild(a);return c};L=function(a){return a.replace(/-+(.)?/g,function(a,f){return f?f.toUpperCase():""})};M=function(a){return d.call(a,function(b,f){return a.indexOf(b)==f})};n.fragment=function(a,b,f){var K,d,g;J.test(a)&&(K=e(k.createElement(RegExp.$1)));K||(a.replace&&(a=a.replace(X,"<$1></$2>")),b===s&&(b=P.test(a)&&RegExp.$1),b in T||(b="*"),g=T[b],g.innerHTML=""+a,
K=e.each(c.call(g.childNodes),function(){g.removeChild(this)}));A(f)&&(d=e(K),e.each(f,function(a,b){if(-1<Z.indexOf(a))d[a](b);else d.attr(a,b)}));return K};n.Z=function(a,b){a=a||[];a.__proto__=e.fn;a.selector=b||"";return a};n.isZ=function(a){return a instanceof n.Z};n.init=function(a,b){var f;if(a)if("string"==typeof a)if(a=a.trim(),"<"==a[0]&&P.test(a))f=n.fragment(a,RegExp.$1,b),a=null;else{if(b!==s)return e(b).find(a);f=n.qsa(k,a)}else{if(h(a))return e(k).ready(a);if(n.isZ(a))return a;if(G(a))f=
r(a);else if(q(a))f=[a],a=null;else if(P.test(a))f=n.fragment(a.trim(),RegExp.$1,b),a=null;else{if(b!==s)return e(b).find(a);f=n.qsa(k,a)}}else return n.Z();return n.Z(f,a)};e=function(a,b){return n.init(a,b)};e.extend=function(a){var b,f=c.call(arguments,1);"boolean"==typeof a&&(b=a,a=f.shift());f.forEach(function(f){E(a,f,b)});return a};n.qsa=function(a,b){var f,e="#"==b[0],d=!e&&"."==b[0],k=e||d?b.slice(1):b,g=ba.test(k);return w(a)&&g&&e?(f=a.getElementById(k))?[f]:[]:1!==a.nodeType&&9!==a.nodeType?
[]:c.call(g&&!e?d?a.getElementsByClassName(k):a.getElementsByTagName(b):a.querySelectorAll(b))};e.contains=k.documentElement.contains?function(a,b){return a!==b&&a.contains(b)}:function(a,b){for(;b&&(b=b.parentNode);)if(b===a)return!0;return!1};e.type=g;e.isFunction=h;e.isWindow=z;e.isArray=G;e.isPlainObject=A;e.isEmptyObject=function(a){for(var b in a)return!1;return!0};e.inArray=function(a,b,f){return t.indexOf.call(b,a,f)};e.camelCase=L;e.trim=function(a){return null==a?"":String.prototype.trim.call(a)};
e.uuid=0;e.support={};e.expr={};e.map=function(a,b){var f,c=[],d;if(C(a))for(d=0;d<a.length;d++)f=b(a[d],d),null!=f&&c.push(f);else for(d in a)f=b(a[d],d),null!=f&&c.push(f);return 0<c.length?e.fn.concat.apply([],c):c};e.each=function(a,b){var f;if(C(a))for(f=0;f<a.length&&!1!==b.call(a[f],f,a[f]);f++);else for(f in a)if(!1===b.call(a[f],f,a[f]))break;return a};e.grep=function(a,b){return d.call(a,b)};window.JSON&&(e.parseJSON=JSON.parse);e.each("Boolean Number String Function Array Date RegExp Object Error".split(" "),
function(a,b){N["[object "+b+"]"]=b.toLowerCase()});e.fn={forEach:t.forEach,reduce:t.reduce,push:t.push,sort:t.sort,indexOf:t.indexOf,concat:t.concat,map:function(a){return e(e.map(this,function(b,f){return a.call(b,f,b)}))},slice:function(){return e(c.apply(this,arguments))},ready:function(a){aa.test(k.readyState)&&k.body?a(e):k.addEventListener("DOMContentLoaded",function(){a(e)},!1);return this},get:function(a){return a===s?c.call(this):this[0<=a?a:a+this.length]},toArray:function(){return this.get()},
size:function(){return this.length},remove:function(){return this.each(function(){null!=this.parentNode&&this.parentNode.removeChild(this)})},each:function(a){t.every.call(this,function(b,f){return!1!==a.call(b,f,b)});return this},filter:function(a){return h(a)?this.not(this.not(a)):e(d.call(this,function(b){return n.matches(b,a)}))},add:function(a,b){return e(M(this.concat(e(a,b))))},is:function(a){return 0<this.length&&n.matches(this[0],a)},not:function(a){var b=[];if(h(a)&&a.call!==s)this.each(function(f){a.call(this,
f)||b.push(this)});else{var f="string"==typeof a?this.filter(a):C(a)&&h(a.item)?c.call(a):e(a);this.forEach(function(a){0>f.indexOf(a)&&b.push(a)})}return e(b)},has:function(a){return this.filter(function(){return q(a)?e.contains(this,a):e(this).find(a).size()})},eq:function(a){return-1===a?this.slice(a):this.slice(a,+a+1)},first:function(){var a=this[0];return a&&!q(a)?a:e(a)},last:function(){var a=this[this.length-1];return a&&!q(a)?a:e(a)},find:function(a){var b=this;return a?"object"==typeof a?
e(a).filter(function(){var a=this;return t.some.call(b,function(b){return e.contains(b,a)})}):1==this.length?e(n.qsa(this[0],a)):this.map(function(){return n.qsa(this,a)}):[]},closest:function(a,b){var f=this[0],c=!1;for("object"==typeof a&&(c=e(a));f&&!(c?0<=c.indexOf(f):n.matches(f,a));)f=f!==b&&!w(f)&&f.parentNode;return e(f)},parents:function(a){for(var b=[],f=this;0<f.length;)f=e.map(f,function(a){if((a=a.parentNode)&&!w(a)&&0>b.indexOf(a))return b.push(a),a});return x(b,a)},parent:function(a){return x(M(this.pluck("parentNode")),
a)},children:function(a){return x(this.map(function(){return F(this)}),a)},contents:function(){return this.map(function(){return c.call(this.childNodes)})},siblings:function(a){return x(this.map(function(a,f){return d.call(F(f.parentNode),function(a){return a!==f})}),a)},empty:function(){return this.each(function(){this.innerHTML=""})},pluck:function(a){return e.map(this,function(b){return b[a]})},show:function(){return this.each(function(){"none"==this.style.display&&(this.style.display="");if("none"==
getComputedStyle(this,"").getPropertyValue("display")){var a=this.style,b=this.nodeName,f,c;m[b]||(f=k.createElement(b),k.body.appendChild(f),c=getComputedStyle(f,"").getPropertyValue("display"),f.parentNode.removeChild(f),"none"==c&&(c="block"),m[b]=c);a.display=m[b]}})},replaceWith:function(a){return this.before(a).remove()},wrap:function(a){var b=h(a);if(this[0]&&!b)var f=e(a).get(0),c=f.parentNode||1<this.length;return this.each(function(d){e(this).wrapAll(b?a.call(this,d):c?f.cloneNode(!0):f)})},
wrapAll:function(a){if(this[0]){e(this[0]).before(a=e(a));for(var b;(b=a.children()).length;)a=b.first();e(a).append(this)}return this},wrapInner:function(a){var b=h(a);return this.each(function(f){var c=e(this),d=c.contents();f=b?a.call(this,f):a;d.length?d.wrapAll(f):c.append(f)})},unwrap:function(){this.parent().each(function(){e(this).replaceWith(e(this).children())});return this},clone:function(){return this.map(function(){return this.cloneNode(!0)})},hide:function(){return this.css("display",
"none")},toggle:function(a){return this.each(function(){var b=e(this);(a===s?"none"==b.css("display"):a)?b.show():b.hide()})},prev:function(a){return e(this.pluck("previousElementSibling")).filter(a||"*")},next:function(a){return e(this.pluck("nextElementSibling")).filter(a||"*")},html:function(a){return 0 in arguments?this.each(function(b){var f=this.innerHTML;e(this).empty().append(v(this,a,b,f))}):0 in this?this[0].innerHTML:null},text:function(a){return 0 in arguments?this.each(function(b){b=
v(this,a,b,this.textContent);this.textContent=null==b?"":""+b}):0 in this?this[0].textContent:null},attr:function(a,b){var f;return"string"!=typeof a||1 in arguments?this.each(function(f){if(1===this.nodeType)if(q(a))for(l in a){var c=l;f=a[l];null==f?this.removeAttribute(c):this.setAttribute(c,f)}else c=a,f=v(this,b,f,this.getAttribute(a)),null==f?this.removeAttribute(c):this.setAttribute(c,f)}):this.length&&1===this[0].nodeType?!(f=this[0].getAttribute(a))&&a in this[0]?this[0][a]:f:s},removeAttr:function(a){return this.each(function(){1===
this.nodeType&&this.removeAttribute(a)})},prop:function(a,b){a=ca[a]||a;return 1 in arguments?this.each(function(f){this[a]=v(this,b,f,this[a])}):this[0]&&this[0][a]},data:function(a,b){var f="data-"+a.replace(Y,"-$1").toLowerCase(),f=1 in arguments?this.attr(f,b):this.attr(f);return null!==f?H(f):s},val:function(a){return 0 in arguments?this.each(function(b){this.value=v(this,a,b,this.value)}):this[0]&&(this[0].multiple?e(this[0]).find("option").filter(function(){return this.selected}).pluck("value"):
this[0].value)},offset:function(a){if(a)return this.each(function(b){var c=e(this);b=v(this,a,b,c.offset());var d=c.offsetParent().offset();b={top:b.top-d.top,left:b.left-d.left};"static"==c.css("position")&&(b.position="relative");c.css(b)});if(!this.length)return null;var b=this[0].getBoundingClientRect();return{left:b.left+window.pageXOffset,top:b.top+window.pageYOffset,width:Math.round(b.width),height:Math.round(b.height)}},css:function(a,b){if(2>arguments.length){var c=this[0],d=getComputedStyle(c,
"");if(!c)return;if("string"==typeof a)return c.style[L(a)]||d.getPropertyValue(a);if(G(a)){var k={};e.each(a,function(a,b){k[b]=c.style[L(b)]||d.getPropertyValue(b)});return k}}var m="";if("string"==g(a))b||0===b?m=p(a)+":"+D(a,b):this.each(function(){this.style.removeProperty(p(a))});else for(l in a)a[l]||0===a[l]?m+=p(l)+":"+D(l,a[l])+";":this.each(function(){this.style.removeProperty(p(l))});return this.each(function(){this.style.cssText+=";"+m})},index:function(a){return a?this.indexOf(e(a)[0]):
this.parent().children().indexOf(this[0])},hasClass:function(a){return a?t.some.call(this,function(a){return this.test(y(a))},u(a)):!1},addClass:function(a){return a?this.each(function(b){if("className"in this){B=[];var c=y(this);v(this,a,b,c).split(/\s+/g).forEach(function(a){e(this).hasClass(a)||B.push(a)},this);B.length&&y(this,c+(c?" ":"")+B.join(" "))}}):this},removeClass:function(a){return this.each(function(b){if("className"in this){if(a===s)return y(this,"");B=y(this);v(this,a,b,B).split(/\s+/g).forEach(function(a){B=
B.replace(u(a)," ")});y(this,B.trim())}})},toggleClass:function(a,b){return a?this.each(function(c){var d=e(this);v(this,a,c,y(this)).split(/\s+/g).forEach(function(a){(b===s?!d.hasClass(a):b)?d.addClass(a):d.removeClass(a)})}):this},scrollTop:function(a){if(this.length){var b="scrollTop"in this[0];return a===s?b?this[0].scrollTop:this[0].pageYOffset:this.each(b?function(){this.scrollTop=a}:function(){this.scrollTo(this.scrollX,a)})}},scrollLeft:function(a){if(this.length){var b="scrollLeft"in this[0];
return a===s?b?this[0].scrollLeft:this[0].pageXOffset:this.each(b?function(){this.scrollLeft=a}:function(){this.scrollTo(a,this.scrollY)})}},position:function(){if(this.length){var a=this[0],b=this.offsetParent(),c=this.offset(),d=R.test(b[0].nodeName)?{top:0,left:0}:b.offset();c.top-=parseFloat(e(a).css("margin-top"))||0;c.left-=parseFloat(e(a).css("margin-left"))||0;d.top+=parseFloat(e(b[0]).css("border-top-width"))||0;d.left+=parseFloat(e(b[0]).css("border-left-width"))||0;return{top:c.top-d.top,
left:c.left-d.left}}},offsetParent:function(){return this.map(function(){for(var a=this.offsetParent||k.body;a&&!R.test(a.nodeName)&&"static"==e(a).css("position");)a=a.offsetParent;return a})}};e.fn.detach=e.fn.remove;["width","height"].forEach(function(a){var b=a.replace(/./,function(a){return a[0].toUpperCase()});e.fn[a]=function(c){var d,k=this[0];return c===s?z(k)?k["inner"+b]:w(k)?k.documentElement["scroll"+b]:(d=this.offset())&&d[a]:this.each(function(b){k=e(this);k.css(a,v(this,c,b,k[a]()))})}});
["after","prepend","before","append"].forEach(function(a,b){var c=b%2;e.fn[a]=function(){var a,d=e.map(arguments,function(b){a=g(b);return"object"==a||"array"==a||null==b?b:n.fragment(b)}),m,l=1<this.length;return 1>d.length?this:this.each(function(a,g){m=c?g:g.parentNode;g=0==b?g.nextSibling:1==b?g.firstChild:2==b?g:null;var n=e.contains(k.documentElement,m);d.forEach(function(a){if(l)a=a.cloneNode(!0);else if(!m)return e(a).remove();m.insertBefore(a,g);n&&I(a,function(a){null==a.nodeName||"SCRIPT"!==
a.nodeName.toUpperCase()||a.type&&"text/javascript"!==a.type||a.src||window.eval.call(window,a.innerHTML)})})})};e.fn[c?a+"To":"insert"+(b?"Before":"After")]=function(b){e(b)[a](this);return this}});n.Z.prototype=e.fn;n.uniq=M;n.deserializeValue=H;e.zepto=n;return e}();window.Zepto=Zepto;void 0===window.$&&(window.$=Zepto);
(function(g){function h(c){return c._zid||(c._zid=u++)}function z(c,d,e,g){d=w(d);if(d.ns)var l=new RegExp("(?:^| )"+d.ns.replace(" "," .* ?")+"(?: |$)");return(v[h(c)]||[]).filter(function(c){return c&&(!d.e||c.e==d.e)&&(!d.ns||l.test(c.ns))&&(!e||h(c.fn)===h(e))&&(!g||c.sel==g)})}function w(c){c=(""+c).split(".");return{e:c[0],ns:c.slice(1).sort().join(" ")}}function q(c){return s[c]||H&&I[c]||c}function A(c,d,e,m,l,p,u){var J=h(c),t=v[J]||(v[J]=[]);d.split(/\s/).forEach(function(d){if("ready"==
d)return g(document).ready(e);var h=w(d);h.fn=e;h.sel=l;h.e in s&&(e=function(c){var d=c.relatedTarget;if(!d||d!==this&&!g.contains(this,d))return h.fn.apply(this,arguments)});var J=(h.del=p)||e;h.proxy=function(d){d=r(d);if(!d.isImmediatePropagationStopped()){d.data=m;var e=J.apply(c,d._args==D?[d]:[d].concat(d._args));!1===e&&(d.preventDefault(),d.stopPropagation());return e}};h.i=t.length;t.push(h);"addEventListener"in c&&c.addEventListener(q(h.e),h.proxy,h.del&&!H&&h.e in I||!!u)})}function C(c,
d,e,g,l){var p=h(c);(d||"").split(/\s/).forEach(function(d){z(c,d,e,g).forEach(function(d){delete v[p][d.i];"removeEventListener"in c&&c.removeEventListener(q(d.e),d.proxy,d.del&&!H&&d.e in I||!!l)})})}function r(c,d){if(d||!c.isDefaultPrevented)if(d||(d=c),g.each(t,function(k,g){var h=d[k];c[k]=function(){this[g]=l;return h&&h.apply(d,arguments)};c[g]=e}),d.defaultPrevented!==D?d.defaultPrevented:"returnValue"in d?!1===d.returnValue:d.getPreventDefault&&d.getPreventDefault())c.isDefaultPrevented=
l;return c}function p(c){var d,e={originalEvent:c};for(d in c)B.test(d)||c[d]===D||(e[d]=c[d]);return r(e,c)}var u=1,D,F=Array.prototype.slice,E=g.isFunction,x=function(c){return"string"==typeof c},v={},y={},H="onfocusin"in window,I={focus:"focusin",blur:"focusout"},s={mouseenter:"mouseover",mouseleave:"mouseout"};y.click=y.mousedown=y.mouseup=y.mousemove="MouseEvents";g.event={add:A,remove:C};g.proxy=function(c,d){var e=2 in arguments&&F.call(arguments,2);if(E(c)){var m=function(){return c.apply(d,
e?e.concat(F.call(arguments)):arguments)};m._zid=h(c);return m}if(x(d))return e?(e.unshift(c[d],c),g.proxy.apply(null,e)):g.proxy(c[d],c);throw new TypeError("expected function");};g.fn.bind=function(c,d,e){return this.on(c,d,e)};g.fn.unbind=function(c,d){return this.off(c,d)};g.fn.one=function(c,d,e,g){return this.on(c,d,e,g,1)};var l=function(){return!0},e=function(){return!1},B=/^([A-Z]|returnValue$|layer[XY]$)/,t={preventDefault:"isDefaultPrevented",stopImmediatePropagation:"isImmediatePropagationStopped",
stopPropagation:"isPropagationStopped"};g.fn.delegate=function(c,d,e){return this.on(d,c,e)};g.fn.undelegate=function(c,d,e){return this.off(d,c,e)};g.fn.live=function(c,d){g(document.body).delegate(this.selector,c,d);return this};g.fn.die=function(c,d){g(document.body).undelegate(this.selector,c,d);return this};g.fn.on=function(c,d,k,m,h){var l,w,r=this;if(c&&!x(c))return g.each(c,function(c,e){r.on(c,d,k,e,h)}),r;x(d)||E(m)||!1===m||(m=k,k=d,d=D);if(E(k)||!1===k)m=k,k=D;!1===m&&(m=e);return r.each(function(e,
r){h&&(l=function(c){C(r,c.type,m);return m.apply(this,arguments)});d&&(w=function(c){var e,k=g(c.target).closest(d,r).get(0);if(k&&k!==r)return e=g.extend(p(c),{currentTarget:k,liveFired:r}),(l||m).apply(k,[e].concat(F.call(arguments,1)))});A(r,c,m,k,d,w||l)})};g.fn.off=function(c,d,k){var l=this;if(c&&!x(c))return g.each(c,function(c,e){l.off(c,d,e)}),l;x(d)||E(k)||!1===k||(k=d,d=D);!1===k&&(k=e);return l.each(function(){C(this,c,k,d)})};g.fn.trigger=function(c,d){c=x(c)||g.isPlainObject(c)?g.Event(c):
r(c);c._args=d;return this.each(function(){"dispatchEvent"in this?this.dispatchEvent(c):g(this).triggerHandler(c,d)})};g.fn.triggerHandler=function(c,d){var e,l;this.each(function(h,r){e=p(x(c)?g.Event(c):c);e._args=d;e.target=r;g.each(z(r,c.type||c),function(c,d){l=d.proxy(e);if(e.isImmediatePropagationStopped())return!1})});return l};"focusin focusout load resize scroll unload click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave change select keydown keypress keyup error".split(" ").forEach(function(c){g.fn[c]=
function(d){return d?this.bind(c,d):this.trigger(c)}});["focus","blur"].forEach(function(c){g.fn[c]=function(d){d?this.bind(c,d):this.each(function(){try{this[c]()}catch(d){}});return this}});g.Event=function(c,d){x(c)||(d=c,c=d.type);var e=document.createEvent(y[c]||"Events"),g=!0;if(d)for(var l in d)"bubbles"==l?g=!!d[l]:e[l]=d[l];e.initEvent(c,g,!0);return r(e)}})(Zepto);
(function(g){"__proto__"in{}||g.extend(g.zepto,{Z:function(h,q){h=h||[];g.extend(h,g.fn);h.selector=q||"";h.__Z=!0;return h},isZ:function(h){return"array"===g.type(h)&&"__Z"in h}});try{getComputedStyle(void 0)}catch(h){var z=getComputedStyle;window.getComputedStyle=function(g){try{return z(g)}catch(h){return null}}}})(Zepto);
$(function(){function g(g,h){var u=w[0],q=u.scrollTop==u.scrollHeight-u.clientHeight;$("<tr><td>"+g+"</td><td>"+h+"</td></tr>").appendTo(w);q&&(u.scrollTop=u.scrollHeight-u.clientHeight)}var h="aisle;bdellium;czar;djinn;Euphrates;fohn;gnarly;irk;hour;jalapenos;knick-knack;llama;mnemonic;ndomo;ouija board;pneumonia;qat;argyle;Szr;tsunami;urn;vraisamblance;wren;Xian;yiperite;Zed Zed Top".split(";");window.conn={};var z=$("#msg"),w=$("#log");$("#name").val(h[Math.floor(Math.random()*h.length)]);var q=
[];$("#form").on("submit",function(g){if(!conn||!z.val())return!1;var h=z.val(),q=$("#name").val();conn.send(JSON.stringify({type:"message",msg:h,name:q}));z.val("");g.preventDefault()});if(window.WebSocket&&window.JSON){var A,C=function(){conn=new WebSocket("ws://"+location.host+"/ws");conn.onopen=function(h){g("<b>Status</b>","<b>Connection established!</b>");setTimeout(function(){conn.send(JSON.stringify({type:"join",name:$("#name").val()}))},10);clearTimeout(A)};conn.onclose=function(h){g("<b>Status</b>",
"<b>Connection closed.</b>");A=setTimeout(C,1E3)};conn.onmessage=function(h){var p=JSON.parse(h.data);h=$("<span/>").text(p.name).html();if("message"===p.type)p=$("<span/>").text(p.msg).html(),g(h,p);else if("join"===p.type)-1==q.indexOf(h)&&($("#users").append("<li>"+h+"</li>"),q.push(h),conn.send(JSON.stringify({type:"join",name:$("#name").val()})));else if("leave"===p.type){p=$("#users").html().replace("<li>"+h+"</li>","");$("#users").html(p);var u=q.indexOf(h);-1!=u&&(q=q.filter(function(g,h){return h!=
u}))}};conn.onerror=function(){console.err(arguments)}};C();window.onbeforeunload=window.onunload=function(){conn.send(JSON.stringify({type:"leave",name:$("#name").val()}))}}else g("<b>Status</b>","<b>Your browser does not support WebSockets and/or JSON.</b></td></tr>")});
